---
- ansible.builtin.apt:
    name: python3-pip

- ansible.builtin.pip:
    name: PyMySQL

- ansible.builtin.stat:
    path: /root/.my.cnf
  register: stat_output

- ansible.builtin.debug:
    var: stat_output

- ansible.builtin.set_fact:
    root_password: "{{ lookup('password', '/dev/null length=15 chars=ascii_letters') }}"
  when: not stat_output.stat.exists

- community.mysql.mysql_user:
    name: root
    password: "{{ root_password }}"
  when: not stat_output.stat.exists

- ansible.builtin.blockinfile:
    path: /root/.my.cnf
    create: true
    block: |
      [client]
      user=root
      password="{{ root_password }}"
  when: not stat_output.stat.exists
